### ISSUE TITLE
render relationship graph

### ISSUE THREAD

**Issue by binford2k** [nwops/puppet-debugger#54]
there should be a command in the web REPL to display the relationship graph in an overlay or popup dialog or some such. This code will render the graph into an SVG, which can be included directly in a webpage for any modern browser.

``` ruby
        node    = Puppet::Node.indirection.find('validator')
        catalog = Puppet::Resource::Catalog.indirection.find(node.name, :use_node => node)

        # Remove some of the noise -- we don't need these nodes rendered
        # These calls are failing due to an internal method not being available in 2 & 3.x. Suspect
        # that it's related to the compiler not being set up fully?
        catalog.remove_resource(catalog.resource("Stage", :main)) rescue nil
        catalog.remove_resource(catalog.resource("Class", :settings)) rescue nil

        dotfile  = catalog.to_ral.relationship_graph.to_dot

        # SVG rendition of the graph
        svg = GraphViz.parse_string(dotfile) do |graph|
          graph[:label] = 'Resource Relationships'

          # change the whits into something readable
          graph.each_node do |name, node|
            next unless name.start_with? 'Whit'
            newname = name.dup
            newname.sub!('Admissible_class', 'Starting Class')
            newname.sub!('Completed_class', 'Finishing Class')
            node[:label] = newname[5..-2]
          end
        end.output(:svg => String)
```

Simply render into a web page:

``` erb
<html>
<head>
  <title>Relationship Graph</title>
</head>
  <body>
        <div class="relationships"><%= svg %></div>
  </body>
</html>
```

**Comment by logicminds** [comment]
@binford2k had to add a lot of new code to get this working.  v0.7.0 now has a plugin and hook system as a result.  This allows for live graph updates.  

See the usage for a live container demo.  The graph gets updated as you add resources which is pretty neat, but I think the presentation could be so much better.  
  * colors
  * better addition logic
  * need event based screen refresh instead of every xx seconds
  * better javascript!  (screen flickers)

https://github.com/logicminds/puppet-debugger-graph#usage

Use the container instructions since it lowers the bar.

**Comment by logicminds** [comment]
closing since I moved to a plugin.
